#!/usr/bin/env python3

"""
STEP 07C
========

Identify Likely Elemental-Analysis Tables

Purpose
-------
Read the complete table inventory generated by Step 07B and
identify tables that are likely to contain elemental composition
information such as C, H, N, O, ultimate analysis, or elemental
analysis.

This step is rule-based and audit-only.

It does NOT:
- change extracted values;
- use an LLM;
- modify the existing extraction pipeline.
"""

from pathlib import Path

import json
import re

import pandas as pd


# ============================================================
# Project paths
# ============================================================

project_dir = (
    Path.home()
    / "Scratch"
    / "hardcarbon_project"
)

processed_tables_dir = (
    project_dir
    / "processed_tables"
)

outputs_dir = (
    project_dir
    / "outputs"
)

tables_jsonl_path = (
    processed_tables_dir
    / "all_tables.jsonl"
)

classified_jsonl_path = (
    processed_tables_dir
    / "classified_elemental_tables.jsonl"
)

classified_csv_path = (
    processed_tables_dir
    / "classified_elemental_tables.csv"
)

classified_xlsx_path = (
    outputs_dir
    / "classified_elemental_tables.xlsx"
)

paper_summary_path = (
    processed_tables_dir
    / "elemental_table_summary_by_paper.csv"
)

# ============================================================
# Configuration
# ============================================================

ELEMENT_NAMES = {
    "C": [
        "c",
        "carbon",
        "total carbon",
        "organic carbon",
    ],
    "H": [
        "h",
        "hydrogen",
        "total hydrogen",
    ],
    "N": [
        "n",
        "nitrogen",
        "total nitrogen",
    ],
    "O": [
        "o",
        "oxygen",
        "total oxygen",
    ],
}

ELEMENTAL_CONTEXT_TERMS = [
    "elemental analysis",
    "elemental composition",
    "ultimate analysis",
    "ultimate composition",
    "carbon content",
    "hydrogen content",
    "nitrogen content",
    "oxygen content",
    "chno",
]

TEMPERATURE_TERMS = [
    "temperature",
    "pyrolysis temperature",
    "carbonization temperature",
    "carbonisation temperature",
    "heat treatment temperature",
    "htt",
]

# ============================================================
# Helpers
# ============================================================

def load_jsonl(path):
    records = []

    with path.open(
        encoding="utf-8"
    ) as source:
        for line_number, line in enumerate(
            source,
            start=1,
        ):
            if not line.strip():
                continue

            try:
                records.append(
                    json.loads(line)
                )

            except json.JSONDecodeError as error:
                raise ValueError(
                    f"Invalid JSON in {path} "
                    f"line {line_number}: {error}"
                ) from error

    return records


def normalize_cell(value):
    if value is None:
        return ""

    text = str(value).lower()

    text = re.sub(
        r"[*_`]",
        "",
        text,
    )

    text = re.sub(
        r"\([^)]*\)",
        " ",
        text,
    )

    text = re.sub(
        r"[^a-z0-9/+%-]+",
        " ",
        text,
    )

    return re.sub(
        r"\s+",
        " ",
        text,
    ).strip()


def exact_element_match(
    cell,
    element,
):
    normalized = normalize_cell(
        cell
    )

    aliases = ELEMENT_NAMES[
        element
    ]

    for alias in aliases:
        if normalized == alias:
            return True

    return False


def contains_ratio_header(cell):
    normalized = normalize_cell(
        cell
    )

    ratio_terms = [
        "h/c",
        "o/c",
        "c/n",
        "h/corg",
        "o/corg",
    ]

    return any(
        ratio in normalized
        for ratio in ratio_terms
    )

# ============================================================
# Table scoring
# ============================================================

def flatten_table_cells(parsed_rows):
    cells = []

    for row in parsed_rows:
        for cell in row:
            cells.append(
                str(cell)
            )

    return cells


def detect_elements_in_table(
    parsed_rows,
):
    """
    Return which CHNO element headers are present.
    """

    detected = set()

    for row in parsed_rows:
        for cell in row:

            if contains_ratio_header(
                cell
            ):
                continue

            for element in ELEMENT_NAMES:
                if exact_element_match(
                    cell,
                    element,
                ):
                    detected.add(
                        element
                    )

    return sorted(
        detected
    )


def contains_context_term(
    text,
    terms,
):
    normalized = str(
        text
    ).lower()

    return any(
        term in normalized
        for term in terms
    )


def score_table(record):
    """
    Score one table for likelihood of containing
    elemental-analysis / CHNO data.
    """

    parsed_rows = record.get(
        "parsed_rows",
        [],
    )

    caption = record.get(
        "caption",
        "",
    )

    preceding_context = record.get(
        "preceding_context",
        "",
    )

    following_context = record.get(
        "following_context",
        "",
    )

    raw_table_text = record.get(
        "raw_table_text",
        "",
    )

    combined_context = " ".join(
        [
            str(caption),
            str(preceding_context),
            str(following_context),
        ]
    )

    detected_elements = (
        detect_elements_in_table(
            parsed_rows
        )
    )

    element_count = len(
        detected_elements
    )

    context_has_elemental_term = (
        contains_context_term(
            combined_context,
            ELEMENTAL_CONTEXT_TERMS,
        )
    )

    table_has_elemental_term = (
        contains_context_term(
            raw_table_text,
            ELEMENTAL_CONTEXT_TERMS,
        )
    )

    context_has_temperature_term = (
        contains_context_term(
            combined_context,
            TEMPERATURE_TERMS,
        )
    )

    table_has_temperature_term = (
        contains_context_term(
            raw_table_text,
            TEMPERATURE_TERMS,
        )
    )

    score = 0

    # Strongest signal:
    # explicit elemental headers.
    score += (
        element_count * 2
    )

    # CHNO-heavy table.
    if element_count >= 3:
        score += 3

    if element_count == 4:
        score += 3

    # Context signals.
    if context_has_elemental_term:
        score += 2

    if table_has_elemental_term:
        score += 2

    if context_has_temperature_term:
        score += 1

    if table_has_temperature_term:
        score += 1

    # Classification
    if (
        element_count >= 3
        or score >= 8
    ):
        classification = (
            "LIKELY_ELEMENTAL_TABLE"
        )

    elif (
        element_count >= 2
        or score >= 4
    ):
        classification = (
            "POSSIBLE_ELEMENTAL_TABLE"
        )

    else:
        classification = (
            "UNLIKELY_ELEMENTAL_TABLE"
        )

    return {
        "detected_elements": (
            detected_elements
        ),
        "element_count": (
            element_count
        ),
        "context_has_elemental_term": (
            context_has_elemental_term
        ),
        "table_has_elemental_term": (
            table_has_elemental_term
        ),
        "context_has_temperature_term": (
            context_has_temperature_term
        ),
        "table_has_temperature_term": (
            table_has_temperature_term
        ),
        "elemental_score": (
            score
        ),
        "classification": (
            classification
        ),
    }

# ============================================================
# Load Step 07B table inventory
# ============================================================

if not tables_jsonl_path.exists():
    raise FileNotFoundError(
        f"Step 07B table inventory not found: "
        f"{tables_jsonl_path}"
    )

table_records = load_jsonl(
    tables_jsonl_path
)

print(
    "Tables loaded:",
    len(table_records),
)

classified_records = []


# ============================================================
# Classify tables
# ============================================================

for record in table_records:

    scoring = score_table(
        record
    )

    classified_record = (
        record.copy()
    )

    classified_record.update(
        scoring
    )

    classified_records.append(
        classified_record
    )

# ============================================================
# Save classified JSONL
# ============================================================

with classified_jsonl_path.open(
    "w",
    encoding="utf-8",
) as output_file:

    for record in classified_records:
        output_file.write(
            json.dumps(
                record,
                ensure_ascii=False,
            )
            + "\n"
        )


# ============================================================
# Build flat classification report
# ============================================================

rows = []

for record in classified_records:

    rows.append(
        {
            "paper_id": (
                record["paper_id"]
            ),
            "source_filename": (
                record[
                    "source_filename"
                ]
            ),
            "table_id": (
                record["table_id"]
            ),
            "paper_table_number": (
                record[
                    "paper_table_number"
                ]
            ),
            "caption": (
                record.get(
                    "caption",
                    "",
                )
            ),
            "detected_elements": (
                ", ".join(
                    record[
                        "detected_elements"
                    ]
                )
            ),
            "element_count": (
                record[
                    "element_count"
                ]
            ),
            "elemental_score": (
                record[
                    "elemental_score"
                ]
            ),
            "classification": (
                record[
                    "classification"
                ]
            ),
            "context_has_elemental_term": (
                record[
                    "context_has_elemental_term"
                ]
            ),
            "table_has_elemental_term": (
                record[
                    "table_has_elemental_term"
                ]
            ),
            "context_has_temperature_term": (
                record[
                    "context_has_temperature_term"
                ]
            ),
            "table_has_temperature_term": (
                record[
                    "table_has_temperature_term"
                ]
            ),
            "non_separator_rows": (
                record.get(
                    "non_separator_rows"
                )
            ),
            "column_count": (
                record.get(
                    "column_count"
                )
            ),
            "raw_table_preview": (
                record.get(
                    "raw_table_text",
                    "",
                )[:500]
            ),
        }
    )

classified_df = pd.DataFrame(
    rows
)

classified_df.to_csv(
    classified_csv_path,
    index=False,
)

classified_df.to_excel(
    classified_xlsx_path,
    index=False,
)

# ============================================================
# Paper-level summary
# ============================================================

paper_summary = (
    classified_df
    .groupby(
        "paper_id",
        as_index=False,
    )
    .agg(
        total_tables=(
            "table_id",
            "count",
        ),
        likely_elemental_tables=(
            "classification",
            lambda values: (
                values
                == "LIKELY_ELEMENTAL_TABLE"
            ).sum(),
        ),
        possible_elemental_tables=(
            "classification",
            lambda values: (
                values
                == "POSSIBLE_ELEMENTAL_TABLE"
            ).sum(),
        ),
    )
)

paper_summary.to_csv(
    paper_summary_path,
    index=False,
)


# ============================================================
# Final summary
# ============================================================

classification_counts = (
    classified_df[
        "classification"
    ]
    .value_counts()
)

print()
print("=" * 70)
print("STEP 07C — ELEMENTAL TABLE IDENTIFICATION")
print("=" * 70)
print()

print(
    classification_counts
)

print()

print(
    "Papers with likely elemental table:",
    int(
        paper_summary[
            "likely_elemental_tables"
        ]
        .gt(0)
        .sum()
    ),
)

print(
    "Papers with likely or possible elemental table:",
    int(
        (
            paper_summary[
                "likely_elemental_tables"
            ]
            + paper_summary[
                "possible_elemental_tables"
            ]
        )
        .gt(0)
        .sum()
    ),
)

print()
print("Generated files:")

print(
    "-",
    classified_jsonl_path,
)

print(
    "-",
    classified_csv_path,
)

print(
    "-",
    classified_xlsx_path,
)

print(
    "-",
    paper_summary_path,
)

